import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UpperNavBar from "./components/UpperNavBar";
import LowerNavBar from "./components/LowerNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-menu Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <UpperNavBar /> */}
        {children}
        {/* <LowerNavBar /> */}
      </body>
    </html>
  );
}
